apiVersion: v1
kind: Service
metadata:
  labels:
    app: "12122"
    app.kubernetes.io/instance: 12122-sample-10010
    app.kubernetes.io/name: deploy-demo-hello
    group: "10010"
    managed-by: triton-io
  name: sample-12122-svc
  namespace: default
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: "12122"
    app.kubernetes.io/instance: 12122-sample-10010
    app.kubernetes.io/name: deploy-demo-hello
    group: "10010"
    managed-by: triton-io
  type: ClusterIP