
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.kruise.io
  resources:
  - clonesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.kruise.io
  resources:
  - clonesets/status
  verbs:
  - get
- apiGroups:
  - apps.triton.io
  resources:
  - deployflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.triton.io
  resources:
  - deployflows/finalizers
  verbs:
  - update
- apiGroups:
  - apps.triton.io
  resources:
  - deployflows/status
  verbs:
  - get
  - patch
  - update
